# Fyers API Credentials
CLIENT_ID = "YOUR_CLIENT_ID"
SECRET_KEY = "YOUR_SECRET_KEY"
REDIRECT_URI = "YOUR_REDIRECT_URI"

# Strategy Parameters
INDIA_VIX_THRESHOLD = 18.0
RSI_OVERSOLD = 25
RSI_OVERBOUGHT = 75
SL_PERCENTAGE = 0.22  # 22%
TP_PERCENTAGE = 0.80  # 80%
CAPITAL_ALLOCATION_PERCENTAGE = 0.20 # 20%
MAX_LOSS_PERCENTAGE_OF_CAPITAL = 0.01 # 1%

# Backtesting Parameters
BACKTEST_YEARS = 5
TIMEFRAME = "5" # 5 minutes
